# Generated by Django 3.1 on 2020-09-03 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time_now',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 3, 6, 24, 48, 948044, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
